spring.application.name=gateway
server.port=8080

spring.cloud.gateway.routes[0].id=bff-route
spring.cloud.gateway.routes[0].uri=http://${BFF_SERVER:localhost:8089}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/bff/**

jwt.secret=${JWT_SECRET_KEY:MiClaveSuperSecretaDe32CaracteresMinimoParaElTokenJWT123!}

urls.frontend=${FRONTEND_URL:http://localhost:3000}