spring.application.name=gateway
server.port=8080

spring.cloud.gateway.routes[0].id=bff-route
spring.cloud.gateway.routes[0].uri=http://localhost:8089
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/bff/**

jwt.secret=MiClaveSuperSecretaDe32CaracteresMinimoParaElTokenJWT123!